services:
  app:
    image: node:22.14.0-bullseye
    depends_on:
      minio:
        condition: service_healthy
      create-buckets:
        condition: service_started
    user: "${USER_ID:-1000}:${GROUP_ID:-1000}"
    working_dir: /usr/src/app
    command: npm run start
    volumes:
      - .:/usr/src/app
    env_file:
      - path: ./.env
        required: true
    mem_limit: 200mb
    # deploy:
    #   resources:
    #     limits:
    #       memory: 200mb

  minio:
    image: minio/minio:RELEASE.2025-02-07T23-21-09Z-cpuv1
    ports:
      - 9000:9000 # API
      - 9001:9001 # console
    volumes:
      - minio:/data
    env_file:
      - .env
    command: server /data --console-address ":9001" --address ":9000"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 3

  create-buckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set my_minio http://minio:9000 adminadmin adminadmin;
      /usr/bin/mc admin info my_minio;
      /usr/bin/mc mb my_minio/test;
      /usr/bin/mc admin trace --verbose my_minio;
      "

volumes:
  minio:
