services:
  rabbitmq:
    image: rabbitmq:3.13.4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_EXCHANGE: batch-exchange
      RABBITMQ_QUEUE: batch-processing-queue
      RABBITMQ_ROUTING_KEY: batch.process
      RABBITMQ_MANAGEMENT_URL: http://rabbitmq:15672
    volumes:
      - ./src:/app/src
      - ./tsconfig.json:/app/tsconfig.json
      - ./nest-cli.json:/app/nest-cli.json
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    command: npm run start:dev
